name: Docker Build CI

# Trigger the build on commits into the master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

# Starts jobs and sets the type of runner they will run on
jobs:
  build-and-publish-to-gh:
    runs-on: ubuntu-latest

    steps:
      - # Checks out repository so your workflow can access it
        name: Checkout 
        uses: actions/checkout@v2
      - # Use docker login
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - # Build and push the image to Container Registry
        name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-runner-base:latest
      - # Build and push the image to Container Registry
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-runner:latest